### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by kevin111615** [SeanChengN/JAViewer#10]
挂梯子进去啥都没有，没列表，搜索也不能用，收藏打开直接显示遇到一个错误，然后重启，怎么解决啊

**Comment by SeanChengN** [comment]
Q3. 界面白屏（由于在线网站的网址变更，也可能是梯子的问题）

A3. 切换无码再切回有码，应用将自动更新网址。搭梯子/换线路，有码的网站被墙，所以要搭梯子。
