### ISSUE TITLE
你修改的APP升级打开网站竟然是原版的github地址

### ISSUE THREAD

**Issue by yinzhefuyun** [SeanChengN/JAViewer#3]
你修改的APP升级打开网站竟然是原版的github地址，APP内的GitHub也是原版的地址，感觉会误导人

**Comment by SeanChengN** [comment]
0226之前的版本应用内升级跳转错误，新版已经修复了，下次更新可以看到效果。出于对原作者的尊重，本不打算修改Github地址，下版本考虑加一个。
