### ISSUE TITLE
加载不出来图片

### ISSUE THREAD

**Issue by a472abpxa** [SeanChengN/JAViewer#5]
进去都正常，就是该显示图片的地方不显示是为什么

**Comment by yjr815jun** [comment]
我也是这样

**Comment by wunai1234** [comment]
我也是 点进去正常 但是一开始显示的封面全是白色的

**Comment by qq2590321055** [comment]
我也是这样

**Comment by clannd327** [comment]
+1

**Comment by SeanChengN** [comment]
不显示图片，但是点击去可以正常显示，目前不知道哪里有问题🤷

**Comment by john9095** [comment]
搜索也不行了

**Comment by SeanChengN** [comment]
@john9095 正常

**Comment by ijlkdmv** [comment]
一样问题，打开app图片全白，点进去可以显示预览

**Comment by 6324-superme** [comment]
还想知道在哪里修改btsow的地址

**Comment by SeanChengN** [comment]
@6324-superme https://github.com/SeanChengN/JAViewer/blob/fuck/app/src/main/java/io/github/javiewer/network/BTSO.java
